spring:
  application:
    name: Shiro_plugin

shiro:
  ws:
    client:
      enable: true
      url: "ws://127.0.0.1:3001"
#      ?????????????????????????
  plugin-list:
      - org.example.shiro_plugin.plugins.ping_test
      - org.example.shiro_plugin.plugins.Get_user_information
